import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const getDeviconClassName = (techName: string) => {
  const normalizedTechName = techName.toLowerCase().replace(/[ .]/g, "").replace(/\+/g, "plus");

  const techMap: Record<string, string> = {
    // JavaScript & TypeScript
    js: "devicon-javascript-plain",
    javascript: "devicon-javascript-plain",
    ts: "devicon-typescript-plain",
    typescript: "devicon-typescript-plain",

    // Frontend Frameworks & Libraries
    react: "devicon-react-original",
    reactjs: "devicon-react-original",
    reactnative: "devicon-react-original",
    nextjs: "devicon-nextjs-plain",
    next: "devicon-nextjs-plain",
    vue: "devicon-vuejs-plain",
    vuejs: "devicon-vuejs-plain",
    angular: "devicon-angularjs-plain",
    angularjs: "devicon-angularjs-plain",
    svelte: "devicon-svelte-plain",
    ember: "devicon-ember-original",
    emberjs: "devicon-ember-original",
    backbone: "devicon-backbonejs-plain",
    backbonejs: "devicon-backbonejs-plain",
    nuxt: "devicon-nuxtjs-plain",
    nuxtjs: "devicon-nuxtjs-plain",
    gatsby: "devicon-gatsby-plain",
    remix: "devicon-remix-original",
    solidjs: "devicon-solidjs-plain",
    solid: "devicon-solidjs-plain",
    astro: "devicon-astro-plain",
    qwik: "devicon-qwik-plain",

    // CSS & Styling
    css: "devicon-css3-plain",
    css3: "devicon-css3-plain",
    html: "devicon-html5-plain",
    html5: "devicon-html5-plain",
    sass: "devicon-sass-original",
    scss: "devicon-sass-original",
    less: "devicon-less-plain-wordmark",
    tailwind: "devicon-tailwindcss-plain",
    tailwindcss: "devicon-tailwindcss-plain",
    bootstrap: "devicon-bootstrap-plain",
    materialui: "devicon-materialui-plain",
    mui: "devicon-materialui-plain",
    bulma: "devicon-bulma-plain",
    foundation: "devicon-foundation-plain",
    stylus: "devicon-stylus-original",

    // Backend Languages
    python: "devicon-python-plain",
    py: "devicon-python-plain",
    java: "devicon-java-plain",
    csharp: "devicon-csharp-plain",
    "c#": "devicon-csharp-plain",
    cpp: "devicon-cplusplus-plain",
    "c++": "devicon-cplusplus-plain",
    cplusplus: "devicon-cplusplus-plain",
    c: "devicon-c-plain",
    go: "devicon-go-original-wordmark",
    golang: "devicon-go-original-wordmark",
    rust: "devicon-rust-original",
    ruby: "devicon-ruby-plain",
    php: "devicon-php-plain",
    swift: "devicon-swift-plain",
    kotlin: "devicon-kotlin-plain",
    scala: "devicon-scala-plain",
    perl: "devicon-perl-plain",
    haskell: "devicon-haskell-plain",
    elixir: "devicon-elixir-plain",
    erlang: "devicon-erlang-plain",
    clojure: "devicon-clojure-plain",
    lua: "devicon-lua-plain",
    r: "devicon-r-plain",
    dart: "devicon-dart-plain",
    fsharp: "devicon-fsharp-plain",
    "f#": "devicon-fsharp-plain",
    groovy: "devicon-groovy-plain",
    julia: "devicon-julia-plain",
    ocaml: "devicon-ocaml-plain",
    zig: "devicon-zig-plain",
    nim: "devicon-nim-plain",
    crystal: "devicon-crystal-original",
    objectivec: "devicon-objectivec-plain",
    cobol: "devicon-cobol-plain",
    fortran: "devicon-fortran-plain",

    // Backend Frameworks
    nodejs: "devicon-nodejs-plain",
    node: "devicon-nodejs-plain",
    express: "devicon-express-original",
    expressjs: "devicon-express-original",
    nestjs: "devicon-nestjs-original",
    nest: "devicon-nestjs-original",
    fastify: "devicon-fastify-plain",
    django: "devicon-django-plain",
    flask: "devicon-flask-original",
    fastapi: "devicon-fastapi-plain",
    rails: "devicon-rails-plain",
    rubyonrails: "devicon-rails-plain",
    laravel: "devicon-laravel-original",
    symfony: "devicon-symfony-original",
    spring: "devicon-spring-original",
    springboot: "devicon-spring-original",
    dotnet: "devicon-dot-net-plain",
    ".net": "devicon-dot-net-plain",
    dotnetcore: "devicon-dotnetcore-plain",
    aspnet: "devicon-dot-net-plain",
    phoenix: "devicon-phoenix-plain",
    gin: "devicon-gin-original",
    fiber: "devicon-fiber-plain",

    // Databases
    mongodb: "devicon-mongodb-plain",
    mongo: "devicon-mongodb-plain",
    mysql: "devicon-mysql-plain",
    postgresql: "devicon-postgresql-plain",
    postgres: "devicon-postgresql-plain",
    redis: "devicon-redis-plain",
    sqlite: "devicon-sqlite-plain",
    oracle: "devicon-oracle-original",
    mariadb: "devicon-mariadb-original",
    mssql: "devicon-microsoftsqlserver-plain",
    sqlserver: "devicon-microsoftsqlserver-plain",
    cassandra: "devicon-cassandra-plain",
    couchdb: "devicon-couchdb-plain",
    dynamodb: "devicon-dynamodb-plain",
    neo4j: "devicon-neo4j-plain",
    firebase: "devicon-firebase-plain",
    supabase: "devicon-supabase-plain",
    prisma: "devicon-prisma-original",
    sequelize: "devicon-sequelize-plain",
    mongoose: "devicon-mongoose-original",
    cockroachdb: "devicon-cockroachdb-plain",
    influxdb: "devicon-influxdb-original",

    // Cloud & DevOps
    aws: "devicon-amazonwebservices-plain-wordmark",
    amazonwebservices: "devicon-amazonwebservices-plain-wordmark",
    azure: "devicon-azure-plain",
    gcp: "devicon-googlecloud-plain",
    googlecloud: "devicon-googlecloud-plain",
    digitalocean: "devicon-digitalocean-plain",
    heroku: "devicon-heroku-plain",
    netlify: "devicon-netlify-plain",
    vercel: "devicon-vercel-original",
    cloudflare: "devicon-cloudflare-plain",
    docker: "devicon-docker-plain",
    kubernetes: "devicon-kubernetes-plain",
    k8s: "devicon-kubernetes-plain",
    terraform: "devicon-terraform-plain",
    ansible: "devicon-ansible-plain",
    jenkins: "devicon-jenkins-plain",
    circleci: "devicon-circleci-plain",
    travisci: "devicon-travis-plain",
    travis: "devicon-travis-plain",
    gitlab: "devicon-gitlab-plain",
    github: "devicon-github-original",
    bitbucket: "devicon-bitbucket-original",
    nginx: "devicon-nginx-original",
    apache: "devicon-apache-plain",
    vagrant: "devicon-vagrant-plain",
    pulumi: "devicon-pulumi-plain",
    argocd: "devicon-argocd-plain",
    prometheus: "devicon-prometheus-original",
    grafana: "devicon-grafana-plain",
    datadog: "devicon-datadog-plain",

    // Mobile Development
    flutter: "devicon-flutter-plain",
    android: "devicon-android-plain",
    ios: "devicon-apple-original",
    apple: "devicon-apple-original",
    xamarin: "devicon-xamarin-plain",
    ionic: "devicon-ionic-original",
    capacitor: "devicon-capacitor-plain",

    // Testing
    jest: "devicon-jest-plain",
    mocha: "devicon-mocha-plain",
    jasmine: "devicon-jasmine-plain",
    selenium: "devicon-selenium-original",
    playwright: "devicon-playwright-plain",
    cypress: "devicon-cypressio-plain",
    puppeteer: "devicon-puppeteer-plain",
    pytest: "devicon-pytest-plain",
    rspec: "devicon-rspec-plain",
    vitest: "devicon-vitest-plain",
    storybook: "devicon-storybook-plain",

    // Build Tools & Package Managers
    webpack: "devicon-webpack-plain",
    babel: "devicon-babel-plain",
    gulp: "devicon-gulp-plain",
    grunt: "devicon-grunt-plain",
    rollup: "devicon-rollup-plain",
    vite: "devicon-vitejs-plain",
    vitejs: "devicon-vitejs-plain",
    npm: "devicon-npm-original-wordmark",
    yarn: "devicon-yarn-plain",
    pnpm: "devicon-pnpm-plain",
    bun: "devicon-bun-plain",
    deno: "devicon-denojs-original",
    esbuild: "devicon-esbuild-plain",
    swc: "devicon-swc-original",
    turbopack: "devicon-turborepo-plain",
    turborepo: "devicon-turborepo-plain",

    // Version Control
    git: "devicon-git-plain",
    svn: "devicon-svn-original",
    subversion: "devicon-subversion-original",
    mercurial: "devicon-mercurial-plain",

    // IDEs & Editors
    vscode: "devicon-vscode-plain",
    visualstudiocode: "devicon-vscode-plain",
    visualstudio: "devicon-visualstudio-plain",
    intellij: "devicon-intellij-plain",
    webstorm: "devicon-webstorm-plain",
    pycharm: "devicon-pycharm-plain",
    phpstorm: "devicon-phpstorm-plain",
    rider: "devicon-rider-plain",
    rubymine: "devicon-rubymine-plain",
    goland: "devicon-goland-plain",
    clion: "devicon-clion-plain",
    datagrip: "devicon-datagrip-plain",
    atom: "devicon-atom-original",
    sublime: "devicon-sublime-plain",
    sublimetext: "devicon-sublime-plain",
    vim: "devicon-vim-plain",
    neovim: "devicon-neovim-plain",
    emacs: "devicon-emacs-plain",
    eclipse: "devicon-eclipse-plain",
    xcode: "devicon-xcode-plain",
    androidstudio: "devicon-androidstudio-plain",
    jupyter: "devicon-jupyter-plain",
    cursor: "devicon-cursor-plain",

    // Operating Systems
    linux: "devicon-linux-plain",
    ubuntu: "devicon-ubuntu-plain",
    debian: "devicon-debian-plain",
    fedora: "devicon-fedora-plain",
    centos: "devicon-centos-plain",
    redhat: "devicon-redhat-plain",
    archlinux: "devicon-archlinux-plain",
    arch: "devicon-archlinux-plain",
    windows: "devicon-windows11-plain",
    windows11: "devicon-windows11-plain",
    windows10: "devicon-windows10-original",
    macos: "devicon-apple-original",
    raspberrypi: "devicon-raspberrypi-plain",
    nixos: "devicon-nixos-plain",
    alpine: "devicon-alpinelinux-plain",
    gentoo: "devicon-gentoo-plain",
    opensuse: "devicon-opensuse-plain",

    // Data Science & ML
    tensorflow: "devicon-tensorflow-original",
    pytorch: "devicon-pytorch-plain",
    keras: "devicon-keras-plain",
    pandas: "devicon-pandas-plain",
    numpy: "devicon-numpy-plain",
    opencv: "devicon-opencv-plain",
    matplotlib: "devicon-matplotlib-plain",
    scikitlearn: "devicon-scikitlearn-plain",
    sklearn: "devicon-scikitlearn-plain",
    anaconda: "devicon-anaconda-original",
    kaggle: "devicon-kaggle-original",
    streamlit: "devicon-streamlit-plain",
    plotly: "devicon-plotly-plain",
    spark: "devicon-apachespark-plain",
    apachespark: "devicon-apachespark-plain",
    hadoop: "devicon-hadoop-plain",

    // CMS & E-commerce
    wordpress: "devicon-wordpress-plain",
    drupal: "devicon-drupal-plain",
    joomla: "devicon-joomla-plain",
    magento: "devicon-magento-original",
    woocommerce: "devicon-woocommerce-plain",
    shopify: "devicon-shopify-plain",
    contentful: "devicon-contentful-plain",
    sanity: "devicon-sanity-plain",
    strapi: "devicon-strapi-plain",
    ghost: "devicon-ghost-original",

    // Game Development
    unity: "devicon-unity-plain",
    unrealengine: "devicon-unrealengine-original",
    unreal: "devicon-unrealengine-original",
    godot: "devicon-godot-plain",
    blender: "devicon-blender-original",
    threejs: "devicon-threejs-original",
    three: "devicon-threejs-original",
    webgl: "devicon-webgl-plain",
    opengl: "devicon-opengl-plain",
    sdl: "devicon-sdl-plain",

    // API & Communication
    graphql: "devicon-graphql-plain",
    rest: "devicon-rest-plain",
    restapi: "devicon-rest-plain",
    grpc: "devicon-grpc-plain",
    socketio: "devicon-socketio-original",
    rabbitmq: "devicon-rabbitmq-plain",
    kafka: "devicon-apachekafka-original",
    apachekafka: "devicon-apachekafka-original",
    postman: "devicon-postman-plain",
    insomnia: "devicon-insomnia-plain",
    swagger: "devicon-swagger-plain",
    openapi: "devicon-openapi-plain",

    // Authentication & Security
    oauth: "devicon-oauth-plain",
    auth0: "devicon-auth0-plain",

    // Blockchain
    solidity: "devicon-solidity-plain",
    ethereum: "devicon-ethereum-plain",
    polygon: "devicon-polygon-plain",
    hardhat: "devicon-hardhat-plain",
    web3: "devicon-web3-plain",
    ipfs: "devicon-ipfs-plain",

    // Design Tools
    figma: "devicon-figma-plain",
    sketch: "devicon-sketch-plain",
    xd: "devicon-xd-plain",
    adobexd: "devicon-xd-plain",
    photoshop: "devicon-photoshop-plain",
    illustrator: "devicon-illustrator-plain",
    aftereffects: "devicon-aftereffects-plain",
    premierepro: "devicon-premierepro-plain",
    canva: "devicon-canva-original",
    inkscape: "devicon-inkscape-plain",
    gimp: "devicon-gimp-plain",

    // Collaboration & Project Management
    slack: "devicon-slack-plain",
    trello: "devicon-trello-plain",
    jira: "devicon-jira-plain",
    confluence: "devicon-confluence-original",
    notion: "devicon-notion-plain",

    // Miscellaneous
    markdown: "devicon-markdown-original",
    json: "devicon-json-plain",
    yaml: "devicon-yaml-plain",
    xml: "devicon-xml-plain",
    latex: "devicon-latex-original",
    bash: "devicon-bash-plain",
    shell: "devicon-bash-plain",
    powershell: "devicon-powershell-plain",
    ssh: "devicon-ssh-original",
    regex: "devicon-regex-plain",
    wasm: "devicon-wasm-original",
    webassembly: "devicon-wasm-original",
    electron: "devicon-electron-original",
    tauri: "devicon-tauri-plain",
    pwa: "devicon-pwa-plain",
    apollo: "devicon-apollo-plain",
    redux: "devicon-redux-original",
    mobx: "devicon-mobx-plain",
    zustand: "devicon-zustand-plain",
    recoil: "devicon-recoil-plain",
    xstate: "devicon-xstate-plain",
    rxjs: "devicon-rxjs-plain",
    lodash: "devicon-lodash-plain",
    d3js: "devicon-d3js-plain",
    d3: "devicon-d3js-plain",
    chartjs: "devicon-chartjs-plain",
    leaflet: "devicon-leaflet-plain",
    mapbox: "devicon-mapbox-plain",
    sentry: "devicon-sentry-original",
    sonarqube: "devicon-sonarqube-plain",
    eslint: "devicon-eslint-plain",
    prettier: "devicon-prettier-plain",
    husky: "devicon-husky-plain",
    axios: "devicon-axios-plain",
    trpc: "devicon-trpc-plain",
    zod: "devicon-zod-plain",
    handlebars: "devicon-handlebars-plain",
    ejs: "devicon-ejs-plain",
    pug: "devicon-pug-plain",
    nunjucks: "devicon-nunjucks-plain",
    liquidjs: "devicon-liquidjs-plain",
    thealgorithms: "devicon-thealgorithms-plain",
    stackoverflow: "devicon-stackoverflow-plain",
    codepen: "devicon-codepen-plain",
    codesandbox: "devicon-codesandbox-plain",
    replit: "devicon-replit-plain",
    glitch: "devicon-glitch-plain",
    linkedin: "devicon-linkedin-plain",
    twitter: "devicon-twitter-original",
    facebook: "devicon-facebook-plain",
    chrome: "devicon-chrome-plain",
    firefox: "devicon-firefox-plain",
    safari: "devicon-safari-plain",
    opera: "devicon-opera-plain",
    edge: "devicon-edge-plain",
    ie: "devicon-ie10-original",
  };

  return techMap[normalizedTechName] || "devicon-devicon-plain";
};
